### ISSUE TITLE
Graphical Frequency coming up invalid with the default study data

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#1063]
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/64556723/552acb38-7345-4645-9b60-58f0a49d32a9)

**Comment by rnugent3** [comment]
I think you might need to tab out of the text box

**Comment by Brennan1994** [comment]
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/64556723/b6fb28ac-d398-4e1b-93d6-51a38c635170)

**Comment by Brennan1994** [comment]
not thinking about the name. Look at those confidence limits. Trying it with some other data here. We're getting weird results, and I think I've tracked it back to the GraphicalDistribution constructor.

**Comment by Brennan1994** [comment]
Was just poking around in Dean's folsom study from sept. and it didn't have the issues.

**Comment by rnugent3** [comment]
@Brennan1994 both cases with borked frequency functions are being caused by illogical inputs. In the first image, you've entered stages but marked flows. Mark stages for stages and you get good frequency bounds. In the bottom image, you have repeated a frequency twice but with different input values. 

Could this be related to the inability of the software to keep track of the user's selection for flow or stage?

**Comment by rnugent3** [comment]
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/2ba0f972-5fdb-48db-b6fa-3492da3efd47)
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/e8045438-f5df-4272-a623-78b2f849295e)
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/653fa2eb-cadb-492d-bd7c-ca77dfcbb0c7)
There is some validation we could build in to avoid this situation. I'll create a dedicated issue for that.
