### ISSUE TITLE
Scenarios > Threshold Stage not saving manually entered values

### ISSUE THREAD

**Issue by rtle76** [HydrologicEngineeringCenter/HEC-FDA#1066]
When a user enters a value for Threshold Stage in a Scenario manually, saves and closes the Scenario, the Threshold Stage is blank upon reopening the Scenario. See below images. 

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/67108837/b37b53b9-5b8c-4f77-b1aa-a10931cec153)

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/67108837/d1540da6-6160-4368-9c51-b58615927554)

**Comment by Brennan1994** [comment]
@rnugent3 @rtle76 
I was unable to reproduce this issue. Appears to work on my end.  Can someone post a study and a workflow to reproduce?

**Comment by Brennan1994** [comment]
Confirmed the value is getting written to XML correctly

**Comment by Brennan1994** [comment]
Confirmed value is loaded into IASElement.SpeciicIASElements.DefaultStage correctly

**Comment by Brennan1994** [comment]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/96f25d0404f35f951954961db3a37080df2d4659/HEC.FDA.ViewModel/ImpactAreaScenario/Editor/SpecificIASEditorVM.cs#L750-L772

**Comment by Brennan1994** [comment]
There's some confusing logic happening here. 

Opening offer: 
- When a user selects a lateral structure, we set the threshold stage to the top of their levee and we uncheck and disable "Scenario Reflects Without Project Conditions." because we're forcing users to use top of levee as the threshold. 
- If the user doesn't select a lateral structure, they set the threshold to whatever they want
- If the "Scenario Reflects Without Project Conditions" is checked, Threshold stage is set to 0 and disabled. (I'm assuming it's not used in this case, and we're going to compute a threshold for them.) 
- If there is a levee selected, 
- if the

**Comment by rnugent3** [comment]
@Brennan1994 I like your approach. I have one suggested refinement to allow a little more flexibility for the direction we're headed with nonstructural performance assessments. That check box - let's name it "Calculate Default Threshold for Non-Leveed Impact Area." 

Entering a target stage needs to be a required field, unless the user selected a lateral structure or the user told us to calculate the default threshold for a non-leveed impact area.

**Comment by Brennan1994** [comment]
is it ever reasonable to request the default threshold for a levee'd area?

I'd like to just disable default threshold and the checkbox whenever there's a levee.
