### ISSUE TITLE
CSVR Normal Distribution Import from TXT File Error

### ISSUE THREAD

**Issue by rtle76** [HydrologicEngineeringCenter/HEC-FDA#1129]
CSVR with a normal distribution of mean 114 and CV of 71.5 imported from TXT

![image](https://github.com/user-attachments/assets/03d7e380-c7e7-4ecd-afdc-e28dea8cdef5)

Should result in normal distribution with a mean of 114 and st dev of 81.51

Does not: 

![image](https://github.com/user-attachments/assets/14ed5679-5342-476d-b3e1-3b8e0182804b)

**Comment by rnugent3** [comment]
A mean of 114 with a CV of 71.5 should produce a standard deviation of 81.5. This is what occurs upon import. 

![image](https://github.com/user-attachments/assets/9db4ba0b-1c18-4b25-9e14-a3a86c7d2ece)

Then, when the imported data is populated in the UI, the standard deviation becomes 92.92. 

![image](https://github.com/user-attachments/assets/b7d49041-fd4c-4942-8a47-1a4f905f348a)

The math is happening twice, I am not sure how. But it is clear that the math is happening twice, because 81.5 * 114 is 92.92.

**Comment by rnugent3** [comment]
I worry that the math shows up in two different places

**Comment by rnugent3** [comment]
I have confirmed that the math takes place twice

**Comment by rnugent3** [comment]
First time: https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/dfb88970ecb9a7b92d3cd1e8e31b7bf28497e51b/HEC.FDA.Importer/ErrorDistribution.cs#L70

Second time: https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/dfb88970ecb9a7b92d3cd1e8e31b7bf28497e51b/HEC.FDA.ViewModel/Utilities/ImportFromFDA1Helper.cs#L674

I am going to remove the first time and rely on the helper class in view model to do all of the work

**Comment by rnugent3** [comment]
Fixed 
![image](https://github.com/user-attachments/assets/ef97627f-cea1-4115-b974-93dd9fd1154e)
