### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#149]
Tooltips showing the data an object was last edited or computed should be added for each child object

**Comment by rnugent3** [comment]
please prioritize

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/170271260-ddc64551-a8bc-41a9-aacf-efc55549d078.png)
All the child nodes have a "Last edited ... " tooltip. Adding a last computed tooltip to nodes that can compute is more difficult. Right now the ias element will update its date every time it saves. When a compute is run i save the results, so the date will get updated. If you open the ias editor and change some values and save, the last edit date will get updated. If we wanted a last computed date, then i have to distinguish between a compute results save, and an editor save. This means adding something to the database and it all gets a bit tricky. If you are ok with just having the last edit date, then this issue is complete.

**Comment by rnugent3** [comment]
I’m good with leaving this for a later version. CC’ing myself to add this functionality to the postponed bells and whistles list. 

Best,

R Nugent III
