### ISSUE TITLE
Does this variable ever get used properly?

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#182]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/9843bc74b18c772ba9b130c52b7cb139ddd8c851/UserControls/CopyPasteDataGrid.vb#L140

Working on translating to C#. This line ```Dim UniqueRows As New List(Of Int32), RowIndex As Int32``` is all over, and I never see anything being assigned to it. Is there some black magic happening here that makes this work, or is this just fluff code. I'd have expected Visual Studio to flag it if it was declared and never used, but it didn't. Just want to make sure I'm not missing something

**Comment by Brennan1994** [comment]
*There does seem to be some places it actually gets used.

**Comment by codymccoy** [comment]
Looks like the one on line 140 can be removed.

**Comment by codymccoy** [comment]
I think the others are being used.
It is bad form (in my opinion) to declare two variables on the same line:
            Dim UniqueRows As New List(Of Int32), RowIndex As Int32
RowIndex should get its own line. All of these "Dim" variables are local to the method. So if it isn't used in the method that it lives in then delete it.

**Comment by HenryGeorgist** [comment]
line 140 could be modified, rowIndex should be declared, but unique rows could be dropped.

the decision needs to be made on a function by function basis, these are all function scope declarations, so you would have to check within the scope of the function.
i agree with Cody, one line multi assignment or declaration are really annoying because it is easy to miss something.

**Comment by HenryGeorgist** [comment]
apparently i should have just read Cody's reply more closely, because we said the same thing.
