### ISSUE TITLE
Fix convergence references in the model 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#243]
The logic depending on convergence in statistics needs to be fixed. Below is a link to one of the locations of a reference to the old convergence logic in statistics. Please update this to the new logic. 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/836702045a9d2b45e6bb19cfcfa36fb453219dfd/Model/Conditions/Locations/Years/Results/ConditionLocationYearResult.cs#L19

**Comment by codymccoy** [comment]
The full list of errors that I am encountering can be found in the branch Occtype_Editor_Investigation.

**Comment by HenryGeorgist** [comment]
why do we need convergence on a year outside of our fda_model?

**Comment by HenryGeorgist** [comment]
if we are using our fda_model for our actual compute, this entire class should get deleted to not cause conflict in terms of using the wrong code

**Comment by codymccoy** [comment]
Many of the errors exist in my code to display the results of the compute. I had to guess at what the results would look like. If there is a new/better way of doing things then we can feel free to change my code. I just need to know what the results object is and i can plug it in.

**Comment by HenryGeorgist** [comment]
it is unwritten, but we shouldnt reference any model objects in our view specifically, we should have a thin veil in our vm. Just create properties unconnected to any model object in your vm at the moment. we will create a converter in the vm to convert the user inputs to model inputs (in the case of input) and to take model outputs and convert them into the vm properties for output.

**Comment by HenryGeorgist** [comment]
i think in this specific case though we are talking about a histogram specifically, since convergence is a property of a histogram itself now

**Comment by HenryGeorgist** [comment]
@rnugent3 is there a specific branch I should be working from?

**Comment by HenryGeorgist** [comment]
I made a commit to #Occtype_Editor_Investigation

I basically just commented out the code that was broken because it does not reference the right model at all, anywhere. If it doesn't reference fda_model, we shouldnt fix, we should remove and exchange it (where applicable). Here it is unclear to me why we have any reference to model.conditions.locations.years.results anywhere in the view model because it is not consistent with the fda_model.
Every fix we make between fda_statistics and the old model is just code debt and potential ground for bugs. 

Our current model in fda_model works well enough to have us support it only.

**Comment by HenryGeorgist** [comment]
we have committed to the new computational model, so we should remove the old one ASAP.

**Comment by rnugent3** [comment]
HEC-FDA/model does not exist anymore, this issue has been resolved
