### ISSUE TITLE
Strong Event References

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#341]
I'm recalling from an earlier discussion with @RyanM-RMA  that wherever we see += we probably ought to see a -= somewhere to avoid memory leaks. I don't recall whether we decided to ignore that problem, or if there's a clever fix somewhere in here that I don't know about. 

Seems like weak event patterns are maybe more appropriate for us, though I'm going to look to you for your expertise. This is something I did not get worked out in my contributions to the code. You'll see this kind of thing in my classes as well. 
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/events/weak-event-patterns?view=netdesktop-6.0

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/b23441b56fe7b5da9950cfb467925fb176ebf06f/ViewModel/FrequencyRelationships/AnalyticalFrequencyEditorVM.cs#L371

**Comment by Brennan1994** [comment]
It also occurs to me that this may be an adaptation of a class I wrote, where I started the pattern. Either way, I'd like your take on it.

**Comment by RyanM-RMA** [comment]
It heavily depends on the lifecycle of your objects.  Weak references are generally preferable to strong references, to a degree.

If you have Class A listen to events on Class B, then B contains the strong reference to A.  This means that A can't be GC'd until B is GC'd.  However, B can be garbage collected, so long as A does not hold a strong reference to B.

If B is a global static rarely changing object, like the Study, you always want to use weak reference listeners, because B's lifecycle is very long, and those strong references will stick around.  Unless that's your intent of course.  You might have a Study level object, then managers or caches that are intended to live as long as the Study.

That's what prompted my previous discussion.  I believe there's a task 14 issue (if we have the money remaining and get approval) to swap over to weak listeners, because all the view models are adding themselves as strong listeners to the Study, and never disappearing.  That's a guaranteed memory leak and processing sink.


The downside to using weak references, is that newbies, or at least people who are unfamiliar with the concept can introduce bugs that take time to resolve.  I've run into this a few times where something gets GC'd before I expect it to be GC'd.  Java has a bit of nuance with this when it comes to anonymous inner classes and lambdas where if you do something like:
```
B obj = new B();
obj.addWeakListener(() -> /*listener logic*/);
//or
obj.addWeakListener(this::listenToEvents);
```
The lambda and method reference will be GC'd at some point, even if it references some class functions or variables.  This will show up as a sporadic bug because GC's happen whenever they want, and sometimes the listener is there, sometimes it's not.  You have to make the lambda into a class variable or something that won't get GC'd to keep it from being destroyed.

Weak and strong refs each have nuance and rules to their use that need to be considered when using them.  That's all I'm getting at.

**Comment by Brennan1994** [comment]
Seems reasonable to me. We can close this guy out. I follow your description, and I'll accept calling this a nice to have fix we can address if we have time on the contract. 

I appreciate the further discussion
