### ISSUE TITLE
RAS Terrains come in slightly different form 

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#347]
Terrains can also come as a single hdf with supporting tifs in the same directory. I will create a Discussion to demonstrate this. 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/b23441b56fe7b5da9950cfb467925fb176ebf06f/ViewModel/Watershed/TerrainBrowserVM.cs#L18

**Comment by Brennan1994** [comment]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/discussions/349

**Comment by codymccoy** [comment]
I left a comment on #349

**Comment by codymccoy** [comment]
I believe we decided to tackle this using maintenance money. @rnugent3 is that correct?

**Comment by rnugent3** [comment]
Correct. 

Best,

R Nugent III

**Comment by codymccoy** [comment]
This is completed. Terrains now support .hdf import. When importing from hdf, we store the name of the hdf file in the sqlite database and we copy the hdf file and all the files at that level into our study directory.

**Comment by rnugent3** [comment]
@Brennan1994 do we want to import all of the files in the terrain directory in which we find the .hdf? For example, in the Muncie terrain folder within Muncie/Hydraulics/Outputs, the prj, tif, and vrt files are brought over too. I imagine if we don't need the .tif because we have the .hdf, we wouldn't want to add the dead weight.

**Comment by rnugent3** [comment]
@Brennan1994 I am not tracking the changes you made regarding this issue. Is there another commit I could take a look at?
