### ISSUE TITLE
Failure to Save:  Entered information or selected parameters in the following dialogs.

### ISSUE THREAD

**Issue by jbslaughter** [HydrologicEngineeringCenter/HEC-FDA#368]
**Build:** CI-CD #41 (Merge pull request #354), dated 2022-05-20

**Create New Study** and **Study Properties** dialogs do not save entered descriptions. Description entered in the Create New Study tab does not display in the Study Properties dialog. 

In the **Study Properties** dialog the following text fields and list selections do not save (the information appears to save because you can close and reopened the dialog and see the entered/modified information), but closing and reopening the study fails to keep the information):

- Study Description
- Discount Rate
- Period of Analysis
- Monetary Unit
- Unit System
- Surveyed Year
- Updated Year
- Updated Price Index

(all text fields appear blank or revert to default values and all combo boxes revert to default selections).

Study Notes entered in the **Study Properties** dialog does not save (closing the reopening the dialog clears the field).

![image](https://user-images.githubusercontent.com/89167848/170356861-a838e799-d5be-47b8-b0b8-a5424ee8b8ad.png)

**Comment by rnugent3** [comment]
killer issue documentation. thanks, @jbslaughter !

**Comment by codymccoy** [comment]
The study properties were not saving because of an ID index issue. That is fixed and everything is saving correctly.

**Comment by codymccoy** [comment]
I have the properties editor open up as a tab instead of a window. Everything else opens as a tab, not sure why this one should be any different. Several fields were not editable but there was nothing in the UI to show this. I now disable the text boxes where the data is not editable. This shows up as gray text to make it more obvious to the user.

![image](https://user-images.githubusercontent.com/47757848/171041947-7c76dd66-3c71-4248-bd73-5a8b72d131ea.png)

**Comment by jbslaughter** [comment]
Correct me if I'm wrong (I'm new to GitHub) - the fix made for this issue has not been (what is the correct term...) merged to the main branch? Therefore, at this point in time new CI-CD builds will not contain this fix, is that correct?

**Comment by rnugent3** [comment]
It's possible. @codymccoy has this fix made it to main yet?

**Comment by codymccoy** [comment]
@jbslaughter @rnugent3 This fix is in main.

**Comment by jbslaughter** [comment]
Is there a way to see that a fix is in the main? I searched the CI-CD workflow and didn't see one for Issue #368. I also don't see a note in the Development section of this issue saying a branch or pull request was made for this issue. Could someone tell me what to look for in a issue (or workflow) to see that a fix has been added to the main CI-CD workflow?

**Comment by codymccoy** [comment]
I don't think there is an easy way to track when a fix goes into main. Usually I am fixing a bunch of stuff in a side branch and then merge it all into main. When I fix a github issue I have started stating what branch the fix is in. Usually it takes about a week for that branch to get pushed back into main. I will try to get my current branch pushed into main today or tomorrow. Once that happens, everything that I have said is fixed will be in main.

**Comment by rnugent3** [comment]
I do my best to refer to issue numbers, but am often working fast and forget.
