### ISSUE TITLE
Message box fetching results 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#454]
I think we need a message box that reads "Processing Results" when we click on "View Results" of an alternative or alternative comparison report. I aspire to make it faster, but those are aspirations only. 

Related: would it make sense to put the processing on a background thread?

**Comment by codymccoy** [comment]
I can't just display a message box because that would lock the UI until the user clicked ok on the message box. I think we should do something similar to what we are doing with the scenario compute. This will require me doing the alternative compute on a background thread and displaying a progress bar or maybe just some text. We should probably do something similar for the alt comp report. I will think about this and see if I can come up with something.
This is the scenario compute UI:
![image](https://user-images.githubusercontent.com/47757848/180818375-0948ee5a-ceee-49cb-9081-06a7cfc94de6.png)
