### ISSUE TITLE
alternatives validation

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#458]
please add validation to check if alternative results has errors and if so what are they

**Comment by codymccoy** [comment]
I added the following block of code.
![image](https://user-images.githubusercontent.com/47757848/180811608-29941b0e-0cc2-466c-85a3-ae5ae8ab5dfd.png)

I wasn't able to test this because my alternative computes were stuck in an infinite loop with the Peres study, and didn't have any errors in my lower cache creek study. 

This change is in the branch results_bug_fixes

**Comment by rnugent3** [comment]
Let's leave this open until we can test. Hopefully the work in the pending PR on fda-model fixes the infinite loop.

**Comment by rnugent3** [comment]
still can't test because of a problem with a dependency's version of .NET
