### ISSUE TITLE
import index points shapefile 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#461]
we need to be able to import a shape file of index points. this will be a point shapefile where the point is the index point. 

@Brennan1994 please provide details as needed.

**Comment by codymccoy** [comment]
After talking with Brennan, we would like to do the following:

We currently use Woody's libraries to write impact area and structure inventory shapefile data to geo package tables in the sqlite database and then get rid of the shapefile.
![image](https://user-images.githubusercontent.com/47757848/181605253-a3bcccb3-8bee-4106-ac95-d1405b9e2032.png)

Since we have removed the map window and don't plan on using Woody's map window going forward, we think it makes sense to stop writing the structure inventory and impact area data to these tables. I don't want to deal with structure inventories at this time, but we propose copying the shapefiles into the study directory like we do with terrains and hydraulics.

We will add two new folders in the study for impact area shapefiles and index point shapefiles.
![image](https://user-images.githubusercontent.com/47757848/181605936-0060e82b-32bc-4a4a-bd31-be4c6f37c019.png)

**Comment by codymccoy** [comment]
The UI for the Index points will be virtually identical to the impact area importer. 
The index point child element will need a new icon made.
The index point child element will have the standard menu items: edit, rename, remove.

**Comment by codymccoy** [comment]
Brennan will need the index points when computing stage damage curves. If we only allow one set of index points then we don't need to update the stage damage UI because we will know what index points to use. If we want to allow multiple index point elements to be created then we will need to add a combobox here:
![image](https://user-images.githubusercontent.com/47757848/181606957-9a4070a5-f0f5-4584-9d74-a955d29e6f6d.png)

**Comment by codymccoy** [comment]
currently, impact areas allow the user to edit the impact area names. I don't see how to make this work if we switch over to simply copying the shapefile to the study directory. Brennan thinks that once we get the ras mapper access working, we should be able to use it to rename impact areas in the shapefile. For the index points, i will not allow the user to edit the names. We can change this down the road.
![image](https://user-images.githubusercontent.com/47757848/181609924-3f013bfa-d5db-44ae-b7d3-ac957e6afeca.png)

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/183765805-446ab797-5b11-44d1-9668-22e38df99f48.png)
unique IDs can be ints, names, doubles, lots of things

**Comment by codymccoy** [comment]
I think all of this work is completed and has been merged into main.

**Comment by rnugent3** [comment]
confirmed.
