### ISSUE TITLE
Uncaught exception create report

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#470]
The "here" hyperlink once did something like create a text file. Now this button just opens an identical window. It would be great to get the text file back. 

![image](https://user-images.githubusercontent.com/25163165/182044659-dc3639f9-d075-492a-a054-d4fe6d1f5ce3.png)

**Comment by codymccoy** [comment]
I clicked the "here" and it behaved as expected and took me here:
https://discourse.hecdev.net/c/fda/33

**Comment by codymccoy** [comment]
@rnugent3 Any further action required on this one? I am not sure what you mean in the original description of a "text file". Clicking "here" should open up an internet browser and take you to the link i posted above.

**Comment by rnugent3** [comment]
![2C77B2A3-6665-46CC-A7B2-5EE673883731](https://user-images.githubusercontent.com/25163165/191148366-0e47e3c6-cd00-4a02-804a-03d3272c6461.GIF)
have you tested in release mode?

**Comment by codymccoy** [comment]
I got latest on main and am now seeing the problem. My guess is that this has to do with the build system. Bringing Brennan in on this one.

**Comment by codymccoy** [comment]
@Brennan1994 , we are seeing an issue with the hyperlink no longer working on the uncaught exception UI. This is the error:
![image](https://user-images.githubusercontent.com/47757848/191310350-baf61252-dfd1-4aaa-bd73-6d98154ecece.png)
![image](https://user-images.githubusercontent.com/47757848/191310368-60f133f6-e937-4a86-9218-e49a2cced252.png)

Since the hyperlink causes another uncaught exception, more windows keep getting added:
![image](https://user-images.githubusercontent.com/47757848/191310476-059456e9-31eb-4baa-b21f-838786a1e51f.png)

**Comment by codymccoy** [comment]
I added a "throw exception" menu item to help us test this.
![image](https://user-images.githubusercontent.com/47757848/191310656-0b919b95-9028-4dc2-9e6c-06f80fb0b2d8.png)

This is in the stage_damage_warning_message branch.

**Comment by codymccoy** [comment]
I grabbed some different code off the internet for launching the hyperlink url. This seems to be working now. Not sure what happened to break the original method. In case it is helpful, this was the error that was being thrown:
![image](https://user-images.githubusercontent.com/47757848/191312290-5131004e-c13a-4d4d-a961-0799ed16198c.png)

I think we can consider this fixed now in branch stage_damage_warning_message

**Comment by rnugent3** [comment]
I'll close this, not sure how we could test without an uncaught exception.
