### ISSUE TITLE
imported stage damage type

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#476]
I am tracking that stage-damage functions imported from 1.4.3 should be of type calculated but on the stage_damage_edited branch they are still being imported as type manual.

**Comment by codymccoy** [comment]
I had the imported stage damage sets marked as manual. I switched it to computed at this line:
![image](https://user-images.githubusercontent.com/47757848/182201385-cfb35d34-31eb-491b-938f-a43b05fba0cb.png)

When you open one of the imported curves for edit, we get the following two pop up messages:
![image](https://user-images.githubusercontent.com/47757848/182201471-dbf48069-9ae7-475e-8f0e-1562865e9b2c.png)

![image](https://user-images.githubusercontent.com/47757848/182201485-3e827496-fd33-44ac-9731-e31befefd730.png)

We get these messages because the imported stage damages don't have hydraulics or an inventory associated with them.

**Comment by codymccoy** [comment]
after clicking ok on the above two message boxes, it opens for edit like this:
![image](https://user-images.githubusercontent.com/47757848/182202109-4a9bbd70-86fc-4044-960f-29cb7ffedf0f.png)

Not really sure how to handle these imported curves. You sure we don't want to call them manual?

**Comment by codymccoy** [comment]
After talking over the phone we decided to keep these as manual for now. 8/1/22
