### ISSUE TITLE
temporarily turn off right click menus

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#514]
We want to temporarily make terrain, hydraulics, structure inventories, and the stage-damage compute editors, right clicks, etc unavailable to prevent confusion around the stage damage compute 

please prioritize this

**Comment by codymccoy** [comment]
Don't allow the user to import a terrain, import hydros, import structures, but do allow the user to create manual stage damages, not computed ones.

**Comment by codymccoy** [comment]
This is fixed in branch bug_fixes.
I created a boolean constant to help track these changes. When we want to revert back to having everything enabled just follow all the references of the constant:
![image](https://user-images.githubusercontent.com/47757848/187245986-274eeaa0-3b7b-481e-8a97-2ba686d8ab64.png)

The computed stage damage editor has the most changes. I disabled the "Computed" radio and added a tooltip:
![image](https://user-images.githubusercontent.com/47757848/187246095-e1ed06f8-7fdc-46ce-b407-de9dbfc3bb0e.png)

I added some notes here:
![image](https://user-images.githubusercontent.com/47757848/187246193-76760a45-e5f2-45c5-9724-df82b04ee4f0.png)

**Comment by rnugent3** [comment]
sorry to do this - we set aside the beta release, so we want these things to be available again. I handled everything except for the stage-damage compute on the plot_with_toolbar branch. thanks for making it super easy to switch with the IS_BETA_RELEASE constant.

**Comment by codymccoy** [comment]
Completed. I updated the stage damages UI to behave like it used to. It defaults to Computed and the computed radio button is enabled. I removed the Is_beta_release constant.

![image](https://user-images.githubusercontent.com/47757848/191316625-5b2af8d5-cd83-4a45-9e90-eac6a641f015.png)

**Comment by rnugent3** [comment]
great, thank you.
