### ISSUE TITLE
alternative compute progress bar appears to not be functional 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#517]
![image](https://user-images.githubusercontent.com/25163165/187008045-0c1cb553-66fb-46bf-8bc3-705d13aab859.png)

**Comment by codymccoy** [comment]
We basically need to determine where can we throw progress events so that I can capture them in the vm.

**Comment by rnugent3** [comment]
I'll look at the compute code and see what I might be able to rig up and get back to you on this

**Comment by codymccoy** [comment]
I added a 100% progress report outside the while loop. I think this is the right place for it. The UI now increments the "completed" number as expected and the progress bar hits 100%.

![image](https://user-images.githubusercontent.com/47757848/193648326-4971059b-444e-4d8b-9472-6583a31d7343.png)

![image](https://user-images.githubusercontent.com/47757848/193648245-e137c648-9600-4397-868d-2d2223362abb.png)

**Comment by codymccoy** [comment]
For the alternative compute, I added a 10% progress at the start of the method and a 100% progress at the end of the compute method.
![image](https://user-images.githubusercontent.com/47757848/193650951-c5e8041b-55f8-4e5f-ba4d-542717b17a8f.png)
![image](https://user-images.githubusercontent.com/47757848/193650971-a630133f-ecce-411b-8b86-1b5b0cf78540.png)

**Comment by codymccoy** [comment]
I similarly updated the alt comp report so that it throws a 10% progress at the beginning of the method and 100% at the end. I also added a simple "start compute" message at the beginning of the alternative compute and the alt comp report compute to make sure that my logic was capturing messages. Feel free to remove those or change them. 
![image](https://user-images.githubusercontent.com/47757848/193679921-0e3c2e24-e692-4197-b60f-648c4d41dc3e.png)
