### ISSUE TITLE
Index point ID can be string or integer

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#518]
![image](https://user-images.githubusercontent.com/25163165/187008589-acaf60ea-04bb-40fd-b864-339cc8237887.png)

**Comment by codymccoy** [comment]
This should be fixed now. Can you please test with whatever file you used. This issue is that if an integer type column was selected as the "Unique Name" column, my cast was throwing the above exception. I guess i was always testing with a string type column. I made the following change which should work for all column types:
Original cast:
![image](https://user-images.githubusercontent.com/47757848/187223810-91c8dfca-6889-4049-981c-7a536235fa42.png)
new "toString" method:
![image](https://user-images.githubusercontent.com/47757848/187223882-dac7141d-cb3e-4300-94ba-fff4590fd8df.png)

fixed on branch bug_fixes

**Comment by rnugent3** [comment]
Confirmed.
