### ISSUE TITLE
software crashes when attempting to view results 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#532]
When launching the software from executable, the software quits when attempting to view scenario results. This does not occur when launching the software from the IDE. This is occurring both on main and on github_issues.

**Comment by rnugent3** [comment]
I can view results using the build I put together a week ago, so this happened recently. 

![image](https://user-images.githubusercontent.com/25163165/189699542-1dc02a57-c6cc-48e2-853e-c74bf1321818.png)

**Comment by rnugent3** [comment]
it just closed the program, no uncaught exception window

**Comment by rnugent3** [comment]
if helpful, it just happened upon attempting to view study properties

**Comment by codymccoy** [comment]
I think it will happen on any UI that uses "UserControls".

**Comment by Brennan1994** [comment]
I'm suspecting this has something to do with the hacky way I was packaging the build before. I'm now using the publish function.  This should be better.

**Comment by Brennan1994** [comment]
Successfully viewing results using a Published build, rather than just a zipped build folder. 

![image](https://user-images.githubusercontent.com/64556723/193643804-116b2ec6-965e-490d-a5d3-4ba3ac5f7fee.png)

The Workflow file has been updates so that we now publish our builds using dotnet publish when we do CI.
