### ISSUE TITLE
create new occupancy types menu item not available 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#536]

**Comment by codymccoy** [comment]
@rnugent3 I am not sure what you are looking for. The occtypes can be created by clicking this button in the occtype editor. An occtypes set must first be imported. Are you wanting a way to create occtypes without importing a set first?

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/191291215-b3d52a6c-4e8c-42c3-92ab-e8a79da1d6ba.png)

**Comment by rnugent3** [comment]
correct - we should be able to either import or create. I thought we had the capability to create an occupancy type group at some point?

**Comment by codymccoy** [comment]
We did. It was a "plus" button in the editor. I took it out when I updated the UI to not handle all the groups, just the occtypes within the group. I think we would need to add a menu item to the parent to "Create New...". It would open up the editor with maybe a single default curve. The user could then go about adding and update as they please?

**Comment by rnugent3** [comment]
sounds good to me

**Comment by codymccoy** [comment]
I added a new menu item:
![image](https://user-images.githubusercontent.com/47757848/191559767-6a356d12-7cb3-4aef-9aa2-7c29ebb33893.png)

The occtype editor opens up blank. The user will need to add a new occtype by clicking the plus button:
![image](https://user-images.githubusercontent.com/47757848/191559890-d106ceec-35bc-4469-bf1d-6da611445fd4.png)

I added validation so that it will not save unless there is at least  one occtype.

![image](https://user-images.githubusercontent.com/47757848/191570530-36b9550a-6c61-4cc0-8654-ae9f075fec9b.png)

**Comment by rnugent3** [comment]
Works as expected. One very minor change, would you please switch the order of the right-click menu items on occupancy types? Most have "create...." on top and then "import...." below.

**Comment by codymccoy** [comment]
Completed:
![image](https://user-images.githubusercontent.com/47757848/200384503-555ece43-b176-4780-88da-0de347499200.png)

This was completed on branch stage_damage_exception branch
