### ISSUE TITLE
view alternative comparison results bug

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#537]
I created an alternative comparison report with a with-project alternative and a without-project alternative. Then, I deleted the with-project alternative. Then, I hit "view results" which led to an uncaught null reference exception.

**Comment by codymccoy** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/47757848/191289918-10cc1bc3-2474-48f1-a704-debcf352d737.png)

I already had the validation logic in place, i just needed to return early in the case that the user is missing alternatives so that later validation checks don't try to use the null values.

![image](https://user-images.githubusercontent.com/47757848/191290163-c31f7bd5-6c9f-4297-9008-464b75b62457.png)

**Comment by rnugent3** [comment]
confirmed thank you
