### ISSUE TITLE
change "import from 1.4.3" to "import tab delimited"

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#540]

**Comment by codymccoy** [comment]
Completed:
![image](https://user-images.githubusercontent.com/47757848/191579705-67872784-68f7-4a08-8ca0-3b3d3a8d6970.png)

All the menu items route to the same place. I just had to update it once.

![image](https://user-images.githubusercontent.com/47757848/191579920-a4a49640-1c01-4f25-839b-e6f4824ea835.png)

**Comment by codymccoy** [comment]
I see that the tab headers were using a different string and were not updated. I will work on that now. Seems like i should make all of those route to the same place so that it is easier to update in the future.
![image](https://user-images.githubusercontent.com/47757848/191600188-771c228d-c245-4620-8fd0-50bb07f3890b.png)

**Comment by codymccoy** [comment]
Completed. "1.4.3" no longer exists anywhere in our code.

I just realized that this was not assigned to me. Sorry if i jumped the gun on this one.

![image](https://user-images.githubusercontent.com/47757848/191608542-369518b4-0704-4730-9e1c-3c65d414d6f7.png)

**Comment by rnugent3** [comment]
I appreciate the initiative! Thank you.

**Comment by rnugent3** [comment]
Issue resolution confirmed
