### ISSUE TITLE
unhandled exception saving stage damage 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#616]
I hit the exception in the image when attempting to save stage-damage functions. I computed the functions using the muncie data, hydraulics are WSE grids. 

![image](https://user-images.githubusercontent.com/25163165/200056520-59a3cf7c-0995-4804-9109-a38336073c4f.png)

**Comment by rnugent3** [comment]
It seems like ImpArea is not being set:

![image](https://user-images.githubusercontent.com/25163165/200149555-c704d1dc-24f7-49b8-98ea-ab46d269b481.png)

**Comment by rnugent3** [comment]
The name of the impact area does not show up:

![image](https://user-images.githubusercontent.com/25163165/200149565-a454e1ff-df50-453d-9420-d46cd79dd487.png)

**Comment by rnugent3** [comment]
@codymccoy this issue is also ready for your attention

**Comment by codymccoy** [comment]
@rnugent3 How do you want to handle this? I think there is another github issue to handle why the impact area names is empty. The exception is because the impact area name is null. I think there are two options here. 
1.) if we expect it to be possible for the name to be null then we need to handle this situation. 
       a.) When the user clicks save we can pop up a message box that says that we can't save because the impact area is empty. I don't think that the name is editable here, so not sure what the user could do about it.
      b.) I can turn that null name into an empty string and save it as an empty string. (or any other default name).
2.) We can ensure that when the curves are getting created that the name is not null. Basically fix the underlying problem. Maybe set a default name if the name is null when generating the curves?

**Comment by codymccoy** [comment]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/issues/576

**Comment by rnugent3** [comment]
Ok. My mistake. I will look into it further. I had put that issue in my backlog for testing.

**Comment by codymccoy** [comment]
For the time being, i have added this logic that at least allows the stage damages to save:
![image](https://user-images.githubusercontent.com/47757848/201987562-a58fbfae-ac3e-447a-aa8f-4a4e3af89adc.png)

**Comment by rnugent3** [comment]
@codymccoy can we make progress on this now?

**Comment by rnugent3** [comment]
4hrs

**Comment by rnugent3** [comment]
To close out this issue, I think we need to add validation to make sure that a name is not null. At the moment, we are able to import impact area sets with null names. @codymccoy thoughts? 
![image](https://user-images.githubusercontent.com/25163165/232167118-86bd59fd-d098-45fb-bd33-6f0ff29bbd36.png)
![image](https://user-images.githubusercontent.com/25163165/232167130-825cced7-37fa-4883-8be2-05bef471df83.png)

**Comment by codymccoy** [comment]
This is a pretty old issue. I am trying to test what the current status is. Currently, the user can't edit the unique name field:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/0f85291c-ce9d-4345-8742-0185c4ad82ac)

I'm guessing that the original issue was that I the user could delete the name and still import. I think this issue is complete.

**Comment by rnugent3** [comment]
@codymccoy plans to work on validation to check for null unique names.
