### ISSUE TITLE
extra space in profile name unhandled exception

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#635]
If the user allows a space after their profile name, we run into an unhandled exception - cannot find part of the path 

![image](https://user-images.githubusercontent.com/25163165/200930153-9790fc2b-cbf2-4b07-87a4-78c49f6bde82.png)

**Comment by codymccoy** [comment]
This is an interesting one. It looks to me like when you create a directory with a space at the end the directory trims that space off. This leads to a mismatch in paths. I will just "trim" the name before I start using it. 

This name property is the one used by most if not all editors. The trim method will remove both leading and trailing spaces. That seems fine to me. I don't see why a user would want either of those.
![image](https://user-images.githubusercontent.com/47757848/200942587-a0d84141-72b0-478a-9b5c-e58af62d78cf.png)

This should fix any other locations where this bug probably would occur also. 

Fixed in branch stage_damage_exception
