### ISSUE TITLE
log file is massive

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#640]
We need to filter what is getting logged. 

![image](https://user-images.githubusercontent.com/25163165/201179110-bce612ac-a23d-40ae-9019-ab271b8a310c.png)

**Comment by rnugent3** [comment]
Part of this work is to define the level of information that we write to file to be fatal and severe. Let's not worry about allowing the user to modify the level of information that can be written just yet - we'll do that for a later version.

**Comment by rnugent3** [comment]
The other part is to confirm that information level is being used judiciously and consistently.

**Comment by rnugent3** [comment]
@codymccoy if you wouldn't mind, I think it would be really helpful to me if you would make sure that all of our AddSinglePropertyRule references have a severity level, and if they do not, let's set the severity level as informational.

**Comment by codymccoy** [comment]
Sounds good to me.

**Comment by codymccoy** [comment]
This is where the log file gets created:
![image](https://user-images.githubusercontent.com/47757848/208525926-a9a7c632-1fc7-428d-bd4b-ad02739b9456.png)

**Comment by HenryGeorgist** [comment]
a permi link would be great.  I think the setting would go on TextFileMessageSubscriber.Instance.LogLevel or something like that. you should have a property on the instance, which you would be able to set from anywhere in the program to change the print level.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/208526867-096cff30-4dfd-4fb1-a3fd-048506935e40.png)

**Comment by HenryGeorgist** [comment]
yeah thats it. i dont remember if it is >= or < in implementation

**Comment by codymccoy** [comment]
If the _maxMessageCount is kept at 100, the messages were not being written to the log file. I changed the max count to be 0 and we still were not getting all the messages to write out. After talking it over with Will, I added a method that flushes the stream writer ever 5 seconds. This seemed to work, but if i change the max count back to 100 I am not getting any messages written out. I think i also need to tell the background worker to dequeue.

Filtering the messages:
Only "IErrorMessage" will get filtered by the error level. There are several places where we are reporting IMessage instead of IErrorMessage. These will always end up getting reported to the log file. I think i should find all of those places and switch them to IErrorMessage and give them an appropriate error level.
![image](https://user-images.githubusercontent.com/47757848/208727517-1c47f5be-c897-4603-9712-8a9e68658736.png)

Many of our property rules do not use the overloaded ctor that allows for an error level. It turns out that this doesn't really matter because we are never directly logging the error messages. We capture them and then report them using a report message call. 

Almost all the messages were coming from PairedData. I added an error level of "Major" and those are no longer getting reported to the log file. The log file has an error filter level of Fatal. 

I have no recollection of doing this, but apparently the error level is changing the color of the messages in the scenario compute. Is that something we want?
![image](https://user-images.githubusercontent.com/47757848/208953570-845f9e4b-2400-4274-9679-f742bd390716.png)

**Comment by codymccoy** [comment]
This is the method that gets called every 5 seconds. @HenryGeorgist does this seem right?
![image](https://user-images.githubusercontent.com/47757848/208955242-86d899c5-f9b3-4228-999a-670c324ca796.png)

With the above logic, i am now getting all the logs written out even if max message count is 100.

**Comment by HenryGeorgist** [comment]
my log text boxes from MVVM framework View components have internal logic to color by severity, if you are using that text box it comes for free.

i would not dequeue on the stopwatch. the max messages in queue is something you can mess with, but this is a fringe case where you are generating a small number of messages on purpose, so i dont think we need to change much to have that happen. id set the max at 1 instead of 0 if we feel we really need to do something, there should be a dequeue statement on the dispose method.

**Comment by HenryGeorgist** [comment]
your code above is not right. you are flushing inside of a while loop effectively. dont do that. flush after the runworker async finishes. dont dupe code, call dequeue at least so that you dont have the logic twice.

**Comment by codymccoy** [comment]
not sure how to do that

**Comment by codymccoy** [comment]
Adding DeQueue to the dispose should get us those last messages when FDA closes right?
![image](https://user-images.githubusercontent.com/47757848/208956854-29a7dc6f-ad6f-4d31-86d9-70669e59e44a.png)

**Comment by HenryGeorgist** [comment]
i think you  need an await on the bw worker too

**Comment by codymccoy** [comment]
It seems like the timed event can just flush the writer.
![image](https://user-images.githubusercontent.com/47757848/208956990-93d4f19f-e9a1-4948-a5f3-dccf67b7cd42.png)

**Comment by codymccoy** [comment]
Yes, I am using a control that you built to display the messages, that is why i don't remember adding color to the messages.
![image](https://user-images.githubusercontent.com/47757848/208957802-469d55a8-6bb4-47ed-b0fa-96dee6331ed7.png)

**Comment by rnugent3** [comment]
@codymccoy I am good with changing just about all messages to error messages. The only message type thing that model sends out that is not an error is the progress reports. Everything else is no news is good news type of situation. 

I have started adding error levels to all add property rules

**Comment by rnugent3** [comment]
> If the _maxMessageCount is kept at 100, the messages were not being written to the log file. I changed the max count to be 0 and we still were not getting all the messages to write out. After talking it over with Will, I added a method that flushes the stream writer ever 5 seconds. This seemed to work, but if i change the max count back to 100 I am not getting any messages written out. I think i also need to tell the background worker to dequeue.
> 
> Filtering the messages: Only "IErrorMessage" will get filtered by the error level. There are several places where we are reporting IMessage instead of IErrorMessage. These will always end up getting reported to the log file. I think i should find all of those places and switch them to IErrorMessage and give them an appropriate error level. ![image](https://user-images.githubusercontent.com/47757848/208727517-1c47f5be-c897-4603-9712-8a9e68658736.png)
> 
> Many of our property rules do not use the overloaded ctor that allows for an error level. It turns out that this doesn't really matter because we are never directly logging the error messages. We capture them and then report them using a report message call.
> 
> Almost all the messages were coming from PairedData. I added an error level of "Major" and those are no longer getting reported to the log file. The log file has an error filter level of Fatal.
> 
> I have no recollection of doing this, but apparently the error level is changing the color of the messages in the scenario compute. Is that something we want? ![image](https://user-images.githubusercontent.com/47757848/208953570-845f9e4b-2400-4274-9679-f742bd390716.png)

I have set up a separate issue to log all of the errors.

**Comment by rnugent3** [comment]
> @codymccoy if you wouldn't mind, I think it would be really helpful to me if you would make sure that all of our AddSinglePropertyRule references have a severity level, and if they do not, let's set the severity level as informational.

I would like to change my mind. Based on the Error Level Discussion #711 we would want to report Major, because the results would not make sense, and the monotonicity problems in paired data would be minor.

**Comment by rnugent3** [comment]
I am debating with myself about whether monotonicity is minor - I will post my self-debate in the discussion.

**Comment by codymccoy** [comment]
@rnugent3 We are getting several messages saying that the impact area scenario results could not be found. Is that a known issue? Should I look into why we are getting that message. I am also not sure why we are getting duplicate messages when initiating and completing the compute.
![image](https://user-images.githubusercontent.com/47757848/209192031-e8d212dc-c65e-4ecb-925f-bb28c70f316f.png)

**Comment by codymccoy** [comment]
This is the method that returns that log message. We are unable to match the impactAreaID.
![image](https://user-images.githubusercontent.com/47757848/209192372-219c0ad8-1143-4ab7-877d-17a51065eef8.png)

**Comment by rnugent3** [comment]
There is an issue created for the duplicate messages and for the messages indicating that something could not be found. I have confirmed that the log file is no longer massive.
