### ISSUE TITLE
Histograms are not writing and reading back properly

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#666]
When testing stage damage curves, it appears that something is wrong with the reading and writing of histograms.

The following code gets triggered when hitting the save button on the computed stage damages UI:
![image](https://user-images.githubusercontent.com/47757848/203397824-f26d863c-4aae-4c8c-9307-49959adc5bba.png)

![image](https://user-images.githubusercontent.com/47757848/203397846-a25d1992-e425-49cc-b3d1-43527d30a331.png)

This is the outputted xml:
![image](https://user-images.githubusercontent.com/47757848/203397897-99a7c8ba-a9bf-4982-b75b-5fd464237105.png)

**Comment by codymccoy** [comment]
I think a unit test is needed to test this.

**Comment by codymccoy** [comment]
This is on branch stage_damage_table_values although that branch is the same as main right now, so feel free to create a new branch if you want.

**Comment by Brennan1994** [comment]
Within UncertainPairedData.ReadFromXML(*) we assume that all Y values will be continuous distributions, which is true. To construct those distributions from XML there is a static method on Continuous Distribution that uses reflection to look for properties with a StoredAttribute, to construct. For whatever reason Threadsafe Inline histogram is not using stored attributes to serialize and deserialize, so the FromXML() method on Continuous distribution doesn't find anything and doesn't instatiate anything. 

That's why we have Zeros.

We can either add some special case logic into the Continuous Distribution.FromXML() method to check for Histograms and handle them differently, or we can refactor Histogram to work more like the other Continuous distributions when it comes to Serialization. 

Option 1 is probably quicker and maintains backwards compatability with existing studies.
Option 2 breaks previous studies, but is probably the better way to handle this. 

@rnugent3 Do you have thoughts?

**Comment by rnugent3** [comment]
Option 2 seems to be the way to go. Is there a way that we can support backward compatibility? If we want the histograms to inherit continuous distribution, we'll need to think of some name refactor, maybe double check the methods because a histogram is not continuous.

**Comment by Brennan1994** [comment]
Thinking about this with a fresh brain, I no longer care about backward compatibility. It just flat doesn't work right now, so why should we care about backward compatible? Not like anybody has been relying on this. 

Unless I'm missing something in my excitement right now, I'm just gonna start trucking on #2 and get it over with.

**Comment by codymccoy** [comment]
I agree, I don't think anyone cares about backwards compatibility for the stage damages. I know I don't.

**Comment by Brennan1994** [comment]
Ok. in the end my solution was not either of the options. Uncertain paired data now checks for the name of the element to match either histogram or Threadsafe histogram, then builds those separately. Since they're not already a continuous distribution, I decided not to shoehorn it. The last pull request should address this.
