### ISSUE TITLE
Impact area name equals bug

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#677]
The following line is working different from what we want. 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/f553032c98a57bcbcd0cc9e5877ed71d1c288366/fda-model/structures/Inventory.cs#L123

I have found that the condition is being evaluated as true despite the strings being different.

**Comment by Brennan1994** [comment]
I'm skeptical of this claim, not because I don't trust you, but because that Equals method is Microsoft's code, not ours.  https://learn.microsoft.com/en-us/dotnet/api/system.string.equals?view=net-7.0#system-string-equals(system-string)

Do you have a unit test you can point me to where I can see this behavior?

**Comment by rnugent3** [comment]
I did not establish a unit test at the time. I just saw it during troubleshooting. I'll work on a test.

**Comment by rnugent3** [comment]
I think the problem is the result of an extraneous semi-colon. That semi-colon at the end of the line of 123 should not be there - and would explain why we step into the conditional block even if the names are not equal.
