### ISSUE TITLE
specific impact area scenarios are incrementing by 2 instead of 1 in the progress bar

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#691]
![image](https://user-images.githubusercontent.com/25163165/206371750-7caa1682-8d74-4759-9d39-c000466f792f.png)

**Comment by codymccoy** [comment]
This is the logic that creates that label:
![image](https://user-images.githubusercontent.com/47757848/206513418-81d115a8-da51-408b-95aa-ba84d13d8ab1.png)

Anytime I get a "100" progress report I increment the iteration number. The compute logic must be throwing too many 100% messages? I will investigate further.

**Comment by codymccoy** [comment]
This is what I think is happening. I think we used to have an issue where it wasn't reporting 100% and so the iteration number wasn't going up like it should. We were maybe getting the last progress report of 99%. I then added a report(100) when it was done and this seemed to fix the problem for that particular study. You are now using a study that does report a 100% and now we are double reporting the 100%. These are the two places that report progress for the scenario:

![image](https://user-images.githubusercontent.com/47757848/206516269-fef7ad57-4d91-4887-92e5-2ae9c82e8a81.png)

![image](https://user-images.githubusercontent.com/47757848/206516304-d6ad932e-e2f7-4246-aea1-098aa4ba8ec3.png)

**Comment by codymccoy** [comment]
Not really sure what to do here. This is kind of complicated code. That first progress report is in a parallel for loop inside a while loop. I'm wondering if we could do something like: if the percentcomplete > 95 then report it as 100% and get rid of the other 100% report?

Another option is to get rid of this label all together?

@rnugent3 Can you send me this study so that I can do some testing?

**Comment by rnugent3** [comment]
[HEC-FDA_Version-2_Study.zip](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/10187831/HEC-FDA_Version-2_Study.zip)

**Comment by codymccoy** [comment]
thanks

**Comment by codymccoy** [comment]
I don't understand what this line is doing? Why are we using mod operator here? Not sure what "need an atomic integer" means either.
![image](https://user-images.githubusercontent.com/47757848/206577499-1e5fa4e5-b046-469c-bcc0-09d6cc00168d.png)

**Comment by codymccoy** [comment]
Ok, i think i have an easy fix that i wish I had thought of earlier. I created some unit tests so that I could look at progress reports easier than going through the UI. The progress report value is dependent on the min and max iterations. I passed in several random min and max values:
![image](https://user-images.githubusercontent.com/47757848/206585765-62971de8-ae18-4f7b-9ab0-57a56a3fe12e.png)

Some combinations produce a max progress value of 100 and some produced a max value of only 99. This is what we had encountered through the UI at various times so I was glad that I could reproduce that. Instead of trying to solve that particular problem, it dawned on me that we know when that particular impact area scenario is done computing (that is where i was throwing the 100% message that was causing the double counting. I vote that we just throw a specific negative number and increment the label when we get that special number. I have chosen -999 and tested it and it worked as we would expect:
![image](https://user-images.githubusercontent.com/47757848/206586039-6dabba4e-6980-4971-9ab7-47096dba8359.png)

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/206586437-5da87dc9-c3d0-4f9d-968b-86826b90479c.png)

**Comment by rnugent3** [comment]
I think this works well. 

We have that hard-coded -999 all over the place to represent unused or absent fields. 

Let's use -1001 for the completion signal? 

Would you mind creating an int constant class in fda-model like your string constant class in view model? This we we avoid hard coding

**Comment by codymccoy** [comment]
I will change it to -1001. I made it a constant so that it is only defined once. I'm not sure that putting it in its own constants class is ideal. 
![image](https://user-images.githubusercontent.com/47757848/206739316-4c9ab2df-ad6e-4eeb-bd53-cb7a49597c4b.png)

**Comment by rnugent3** [comment]
Thanks. What seems unideal about having the constant in a dedicated class?

**Comment by codymccoy** [comment]
maybe "ideal" was the wrong word. Maybe unnecessary is more what i meant. Like most things, it would be fine either way. I was just thinking that classes should be responsible for their stuff. If we don't expect anyone else to use this value, then it seems like it should just live with the class. The string constants class in the view model I think has the added benefit of being able to see all the menu items in one place so that if we want to change the wording it is easy to update. I don't think we will need to do much updating on this value since it is an int and putting it in a class all by itself seems unnecessary. But it doesn't really matter to me either way. If you want to have a class where going forward we put all the constant integers that is fine.

**Comment by rnugent3** [comment]
We can leave it for now. Eventually I'll want a constant for the -999 stuff, I'm afraid of having a conflict with the wrong number of 9s. That can wait.

**Comment by codymccoy** [comment]
I agree that we should not be using -999 in multiple places. It should be defined once, probably as a static that can be used from all over. I guess the question is should that static value be defined in an existing class or in its own class.
