### ISSUE TITLE
change default updated price index to 1.0 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#692]
![image](https://user-images.githubusercontent.com/25163165/206372371-df538baa-b274-4aee-b47f-550b6d65f6c6.png)

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/206499353-70864c69-9db9-4978-995d-e824c059cd8e.png)

This value will not automatically update existing studies because that value has been written to the database. New studies will show up like the image above.

This is fixed in branch update_index

**Comment by rnugent3** [comment]
Understood. Thank you!!
