### ISSUE TITLE
It may not be necessary to rebin the histogram when data is added.

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/HEC-FDA#746]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/b28616e688540d279c999c05c3adb91909c7be0c/Statistics/Histograms/Histogram.cs#L334

I'm noticing extremely long runtimes on my test study, upwards of an hour for a single reach with ~300 structures, and nearly 40% of the cpu time is spent on this method, which appears to be that every iteration it is writing each result to the histogram, a method which itself contains for loops used to rebin the histogram. So at that stage there are at least 4 nested loops leading to an extreme number of calculations. 

I'm still reading through this to be sure, but since the calculations performed in the AddObservationToHistogram method probably don't need to be done until metrics are pulled from the final histogram (such as by the MeanExpectedAnnualConsequences function in ConsequenceDistributionResult) they could instead be done on the backend reducing the number of times they need to be performed exponentially. It seems like the AddObservationToHistogram could do little else besides add double values to a list or array, and a seperate rebinning method could be called by properties that return mean, exceedance probabilities, etc..

**Comment by HenryGeorgist** [comment]
so in the binning algorithm it doesnt rebin every time. only if the observation is below the minimum bin edge or above the maximum bin edge.  then it does an array buffer copy to create extra bins and place the observation in the correct new bin.

all data is binned only once, this is done with each observation so we can check for convergence without keeping the array of data.

we are encoding the doubles to a list of bins that have an int in each array position, so that we have a smaller memory footprint for the observations we generate.

**Comment by AlexRyanUSACE** [comment]
So i did some probably incorrect back of the envelope stuff on my end and just the computelowerstagedamage method would generate nearly 10 gigs of data for a small inventory like my test one if running the max of 500,000 iterations. So yeah, obviously a balancing act between performance and memory consumption. Maybe an alternate solution would be to store the data as a list of double values for a single run through x iterations (500,000 would generate ~4 megs then of memory usage in my example above), and then apply a version of the logic currently in AddObservationToHistogram at the end of that chunk and clear out the stored doubles. This would still dramatically increase performance (i think?) by executing that logic hundreds of thousands of times less frequently, but still increase memory usage by a very small amount. I'll have to look into it further though as this is kind of a half formed thought...

**Comment by HenryGeorgist** [comment]
so the only expensive operation is the buffer byte copy. it should happen infrequently. we use an initial sample of min iterations to set the range and size of the bins (through sturges rule) that way we should only be getting buffer byte copies about 1percent of the time or less. actually indexing the bin's location in a loop vs on each iteration is not a huge committment of resources (i dont think)
i built the threadsafe version to queue the observations and flush them on a background thread, but it just does the same work on a separate thread so that the compute thread keeps running full blast. we tried using the threadsafe inline histogram and couldnt find justification for it in our initial testing, maybe we should look at that again after the refinements in our last iteration.

**Comment by HenryGeorgist** [comment]
doing the operation of add observation in a loop only removes the overhead of the method call, the same work gets performed if we do it in batches. we arent rebinning all values, just the current value at each call. so each new observation just goes through the method. to make a histogram all observations have to go through the logic at some point, we only do it once per observation.

**Comment by HenryGeorgist** [comment]
is this ok to close?

**Comment by AlexRyanUSACE** [comment]
Yeah, i haven't been able to reproduce the add observation method hogging performance, and your reply above makes total sense, so best guess is i was doing something wrong or weird that run and the profiler results were erroneous.
