### ISSUE TITLE
Uses stages not flows is being set incorrectly 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#753]
I have a study where the data uses a graphical flow-frequency function and a stage-discharge function. On the graphical frequency function, UsesStagesNotFlows should be false but it is true: 

![image](https://user-images.githubusercontent.com/25163165/216785744-72470c60-a5ea-4866-b5bf-799d4e0e45c3.png)

**Comment by rnugent3** [comment]
I tried to fix this, but failed.

**Comment by codymccoy** [comment]
I believe i have fixed this. 
Here is a graphical using flows:
![image](https://user-images.githubusercontent.com/47757848/217101907-27c87cc4-6538-4d94-90d9-176611360c01.png)

On line 133 there is a ctor that defaults the last 3 values. When this ctor was being called, the calling class was not passing that information in, so it was always getting defaulted to "true".
![image](https://user-images.githubusercontent.com/47757848/217102155-481f538f-d5e7-409a-975b-08d94f9535ec.png)

I now pass in the boolean. I had to do the opposite value because that class stores if it is using flows.
![image](https://user-images.githubusercontent.com/47757848/217102228-61528867-bada-4884-a844-573a2d90d060.png)

What about the min and max values? Should those be using the default or should we be passing those values in?

**Comment by codymccoy** [comment]
This bug was fixed in the graphical_frequency_bug branch.

**Comment by rnugent3** [comment]
Could you please do a test? I think I made the same change (but didn't commit) over the weekend and it didn't work for me. Of course whenever I am in the VM or V I am pretty clueless. 

A way to test would be to use a graphical flow-freq and rating curve for a stage damage compute. Then make sure that stages are on the x axis, not flows.

**Comment by codymccoy** [comment]
Ok, testing.

**Comment by codymccoy** [comment]
You are right, this did not fix it. I am looking into it.

**Comment by rnugent3** [comment]
Thank you sir

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/217112897-85ebb7b6-2439-4a72-bd2f-45b901254816.png)
I think this is the problem. Is there a reason that this argument has a default of true. I feel like we should remove the default and force everyone calling it to specify if it is stages or flows.

**Comment by codymccoy** [comment]
Changing the above line to use the actual value fixed the issue (i think). Stages are on the x axis:
![image](https://user-images.githubusercontent.com/47757848/217113670-d86914ec-d17c-49ce-85c0-3e056a37c0c8.png)

I removed the default value for that argument so that you have to tell it what value to use. I had to update one unit test by passing in "true".

**Comment by rnugent3** [comment]
Huh. So are we having trouble overriding the default value? 

I can't remember exactly why I put the default value there but I have a guess - I probably added the parameter after the constructor had been in use and I didn't want to break stuff. 

If clearing the default value does the trick then im supportive - but I'd also like to learn more about why the default value couldn't be overridden

**Comment by codymccoy** [comment]
The default value can be overriden but if you look at this pic, the value is hard coded to true instead of passing in the correct value.
![image](https://user-images.githubusercontent.com/47757848/217114171-9a19a7b2-fe6e-4fb8-ba60-bf650fa4fbf5.png)

**Comment by codymccoy** [comment]
We ran into two places where the value was getting set to true no matter what. One was because we didn't pass in an argument so it was getting defaulted to true. The other one we were always passing in true instead of asking the property what the correct value was.

**Comment by codymccoy** [comment]
I get what you mean about adding to the ctor after the code has been there a while and not wanting to break things, but i think in this case that is an argument that we don't want to be left up to chance.

**Comment by rnugent3** [comment]
Cool. Thanks for making this work.
