### ISSUE TITLE
confidence limits for 0-meaned histos are wrong

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#755]
![image](https://user-images.githubusercontent.com/25163165/216786913-9f420889-3309-4d5c-a815-00a4a4174416.png)

**Comment by codymccoy** [comment]
@rnugent3 What should they be? 0?

**Comment by rnugent3** [comment]
Correct - should be 0

**Comment by codymccoy** [comment]
I can't reproduce this. If I use the same selections as in your screen shot then I run into the NPE described here: #761. If I use the clipped structures I get results that have zero values:
![image](https://user-images.githubusercontent.com/47757848/217375155-b62670ae-2f3e-4268-a7be-cb6ae24de1be.png)

@rnugent3 If you are able to reproduce this, send me the study and I will take a look. Maybe there was some code changes that happened since posting this issue that are now causing #761?

**Comment by rnugent3** [comment]
probably...the issue came up while I was working on the stage damage refactor branch. you could pull that branch or wait until we finish out PR #752 and merge.

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/218221447-9ca9829e-9782-463d-b0a4-bb8b479fb7fa.png)
fixed
