### ISSUE TITLE
scenario workflow is bad

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#818]
There are a few clunky parts of the scenario workflow. Two I am tracking right now:

1. The impact area combo box is not in an intuitive location - I think it should be grouped with the impact area level data entry 

![image](https://user-images.githubusercontent.com/25163165/222770642-07a13f9d-d168-4493-bb77-a6d1432c18ff.png)

2. It makes the user uncomfortable to move onto the next impact area without saving

**Comment by rnugent3** [comment]
Year should be an optional field for documentation purposes, and relabeled "Year(s)" to allow for one scenario to represent multiple analysis years. Let's assign the year when we create the alternative.

![image](https://user-images.githubusercontent.com/25163165/223199896-2b32e238-e43c-41ee-bdee-92e605af186a.png)

**Comment by rnugent3** [comment]
let the impact area selection be its own row

**Comment by rnugent3** [comment]
we can let the user save whenever - we'll have to do the validation on the model side

**Comment by Brennan1994** [comment]
Prevents user from getting critical information : NO
Saves to disk in a way that would be hard to support going forward if we release as is: NO
Is difficult enough to use that it would be embarrassing to release: YES

**Comment by rnugent3** [comment]
allow the user to save in an error state or incomplete state

**Comment by rnugent3** [comment]
we'll want a pop up "you have not finished the job"

**Comment by Brennan1994** [comment]
4hrs

**Comment by codymccoy** [comment]
I believe that this issue is not completed in branch scenario_workflow_818. 
There is a new scenario UI design where each impact area gets its own tab. 
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/478b1dd1-a345-4615-8541-aaf3ee273016)
I added an icon next to the tab header that will be a red exclamation if there are errors that will prevent a compute, and a green checkmark if that impact area is valid to compute. There is a tooltip on the header if there is a red exclamation that describes the issues.

I added new UI elements for "Scenario Reflects Without Project Condition" and "Default Stage".
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/60c7ebac-5ff5-4966-9a6f-249b0c44f6e5)
The checkbox is selected by default, the default stage gets a read star, meaning it is required, if the checkbox is not selected and the user doesn't have a lateral structure selected.

**Comment by codymccoy** [comment]
I made several updates to the Thresholds:
It used to say "Add Additional Thresholds..." I changed that to "Additional Thresholds..." because i see it as more of a place to manage the additional thresholds and not just add. There is a remove option. Or you can edit the existing stage value.
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/063cfebc-718a-44da-b0fb-f7c32b2f905e)

I also removed the "Copy" button because it didn't really serve any purpose anymore:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/57df6325-6dfd-4850-a5f4-b1b874d50c5b)

The only editable field now is the stage value. The threshold type is always set as "Additional Exterior Stage". There was a lot of bad behavior in this UI. I switched it from a list view into a datagrid. If there are validation errors, then clicking ok will display the errors (ie: no repeat stage values) and will not close the editor. If you click the red X then the UI will close and will not save any changes that were in that UI. The user must also click the Save button on the parent UI to actually save any threshold changes.

**Comment by codymccoy** [comment]
I am not sure if there was another github issue for the alternative editor UI changes. I didn't see one so i will describe those changes here:
The alternative editor UI shows two rows with comboboxes for the scenarios and then a year field. I default the year field to be the current year.
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/acc3c4c0-a6a8-4b50-88d8-51432214a3ff)

Changes were made so that the year in the scenario editor is an optional string. The year field in the Alternative editor is what we will use for computes. There is validation on the save click that makes sure the base year is before the future year and that the selected scenarios are different.

**Comment by codymccoy** [comment]
This unit test is failing because there is an "unassigned" dam cat getting returned. Not sure if my code is causing that or not.
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/3ffc3c0a-166e-4823-958f-a21a17172497)
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/7a4643dd-4b00-442b-b817-31463902006f)

**Comment by rnugent3** [comment]
This test is no longer failing and the result looks good
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/32dfc3d7-ca86-443c-b067-61aea4efc3fd)
