### ISSUE TITLE
Plots appear the same

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#831]
Kurt B reported that two plots that should be different, look the same: 
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/25163165/224404913-d6a8acc8-21e6-4273-b390-9fb52fdd0521.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/25163165/224404919-b69142b5-68f0-4c74-83f0-7420f6816320.png)

**Comment by Brennan1994** [comment]
8hrs

**Comment by Brennan1994** [comment]
@rnugent3 do you have a study that shows this behavior I can grab?

**Comment by rnugent3** [comment]
https://www.hec.usace.army.mil/confluence/download/attachments/133992889/WS6_Part2_Solution.7z?api=v2

**Comment by Brennan1994** [comment]
This bug is more complex than expected. The current chart is SciChart. There's some hacky code that handles data context switching that makes it work. There's a history of issues with this control. After discussion with @codymccoy we think the right way to handle this is to move it to OxyPlot. Changing time estimate to 16 hours.

**Comment by codymccoy** [comment]
I built an oxyplot control that has a toolbar. It is called PlotWithToolbar. That is what is being used in the TableWithPlotControl that we use in the other editors. I would look at those uses to see how it is being used.
![image](https://user-images.githubusercontent.com/47757848/229149847-34d68181-b793-42d7-bc56-9cb40cd1d31b.png)
