### ISSUE TITLE
Occupancy Type Bug - Content Value Uncertainty Entry Isn't Functioning Properly

### ISSUE THREAD

**Issue by rtle76** [HydrologicEngineeringCenter/HEC-FDA#877]
I entered Occupancy Types three different ways in one model and there are inconsistencies in the results. It seems like the selections in the UI are not always consistent with what is showing in Locals when I run the model in debug mode.

 

1. As entered in the UI:

Occupancy Type is GOV1

Vehicle Damage is unchecked

Other Damage is unchecked

Content input is By Content Value

Distribution Type is Triangular Min 13% Max 4.2%

See below

 ![Gov1OccType](https://user-images.githubusercontent.com/67108837/234775503-4038986d-f3c3-4b1b-9ad6-41ed9c1cce9f.png)

As shown in Locals:

ComputeVehicleDamage should be false

ComputeOtherDamage should be false

UseContentToStructureValueRatio should be false

Distribution type and parameters are correct

See below

![PUB](https://user-images.githubusercontent.com/67108837/234775633-403b237b-d4c7-4d8c-9b7d-439fe69a8f95.png)
 

Aggregated Stage-Damage Funcion: Shows structure damages, but no content damages

See below

![PubStruc](https://user-images.githubusercontent.com/67108837/234775693-8bf8033e-e4ab-4d72-8cb3-486eee7d2e82.png)
![PubCont](https://user-images.githubusercontent.com/67108837/234775701-4a182122-cb19-4006-9f79-7ad0d0a01d03.png)

2.

As entered in the UI:

Occupancy Type is COM1

Vehicle Damage is unchecked

Other Damage is unchecked

Content input is By Content-to-Structure Value Ratio

Distribution Type is Triangular Min 15% Most Likely 87.5% Max 95%

See below.

 ![Com1OccType](https://user-images.githubusercontent.com/67108837/234775781-64452295-ca6b-4a3d-9a94-cf854907fa57.png)

As shown in Locals:

ComputeVehicleDamage should be false

ComputeOtherDamage should be false

UseContentToStructureValueRatio should be true

Distribution type and parameters are incorrect

See below

![COM](https://user-images.githubusercontent.com/67108837/234776001-79b47a37-4590-4483-b5ce-dafeedb7ae1c.png)

 
Aggregated Stage-Damage Funcion: Shows structure damages and content damages

See below

![ComStruc](https://user-images.githubusercontent.com/67108837/234776105-2e769b52-cc0a-4f81-8538-21390d84d845.png)
![ComCont](https://user-images.githubusercontent.com/67108837/234776115-3efa4517-37b5-4142-b350-6b065b72b04c.png)
 

3.

As entered in the UI:

Occupancy Type is RES1-1SNB

Vehicle Damage is unchecked

Other Damage is unchecked

Content input is By Content Value

Distribution Type is Deterministic

See below

 
![RES1-1SNB](https://user-images.githubusercontent.com/67108837/234776221-e0150491-482f-454b-9eeb-0ce0edd0a20e.png)

As shown in Locals:

ComputeVehicleDamage should be false

ComputeOtherDamage should be false

UseContentToStructureValueRatio should be false

Distribution type and parameters are correct

See below

 
![RES](https://user-images.githubusercontent.com/67108837/234776293-23fc00f0-6ddc-4a51-9d40-49da817b2801.png)

Aggregated Stage-Damage Funcion: Shows structure damages and content damages

See below

 
![ResStruc](https://user-images.githubusercontent.com/67108837/234776337-2536d469-0fb2-4e6b-8f27-c7e70abb7bc1.png)
![ResCont](https://user-images.githubusercontent.com/67108837/234776342-41226e60-3f4d-43f1-b14b-ee2415669550.png)

Content damages aren’t being computed when the input method is By Content Value and the Distribution Type is Triangular, but it’s hard to tell if that’s a UI or compute issue.

**Comment by rnugent3** [comment]
@codymccoy I am going to pass this to you. I have attached the study I used to confirm Jordan's findings. 

1. No replication steps needed to verify that occupancy types are different in the model from how they appear in the user interface. Simply run a stage damage compute, put a breakpoint at the below location, choose any one of the occupancy types that Jordan mentions above, and compare what you see in locals vs what you see in the occupancy type editor. 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/d8cee274362fe02b7cb040dadb0d0ab7b416b94b/HEC.FDA.Model/structures/Inventory.cs#L328

2. I have changed the occupancy types in the attached study so that all public occupancy types use content value uncertainty with a triangular distribution, but I have only recomputed the existing stage-damage set of stage-damage functions. To replicate the bug where content damage is not computing for an occupancy type with content value uncertainty/triangular distribution, take a look at existing_future stage-damage functions and observe that there is positive content damage for the public damage category. Then, recompute so that content value is obtained differently with the updated occupancy types, and observe that content damage is zero for the public damage category. 

[WS6.zip](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/11751606/WS6.zip)
