### ISSUE TITLE
Curve Overlap Mess

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#921]
We're using validation that checks to make sure that input curves are reasonably overlapping to avoid a flat distribution. Flat distributions cause unhandled exceptions in Histogram. As I recall, the flat distribution caused variance to go to something infinitely close to zero and then we tried to do math with that number and the computer said nope? In any case, we had bad data being passed from the impact area scenario simulation to histogram. I will try to find the issue where we tracked this work. 

In the meantime, it's worth thinking about whether this is the correct solution. Here are my thoughts: 

- The problem is caused by bad data. Our current posture is to quit the compute if we detect bad data rather than attempting to carry through the math on a flat distribution. Whether we're effectively assessing the validity of the data is a very open question for me. 
- The problem occurs in the Histogram class, which lends appeal to handling the issue in the histogram class. The math was not written to handle the bad data, so maybe we should re-write the math to allow the compute to continue and set any bad data aside. 

@Brennan1994 what do you think?

**Comment by Brennan1994** [comment]
If this is an issue of bad input data I'm partial to sanitizing that data, or rejecting it, rather than rewriting the compute to handle bad stuff. 

What I think we need to move forward is identifying what entails bad data. I'm still uncertain. It seems like it might change per curve combination. I tried to split up the validation fine enough that we could be as custom or generic as we want, but we need to write up or code up clear requirements.

It's super easy to make sure the X values of one curve have the exact same range as another. If that's the case, we can do that. I'm just not sure which curves require that, and which don't. 

Seems like maybe some need TOTAL overlap, and some have to match in the middle, but can be short on either the low or high  ends without being unreasonable (for example, a fragility curve that stops at top of levee, rather than going all the way to the top of the stage freq.

**Comment by Brennan1994** [comment]
This commit referenced in this may be useful for implementing curve overlap validation in the future.
